name: Check Source Branch
description: Validate that the PR source branch is allowed.

inputs:
  allowed_branches:
    description: Comma-separated list of exact branch names allowed (e.g., dev,staging)
    required: false
    default: dev
  allowed_prefixes:
    description: Comma-separated list of allowed branch prefixes (e.g., hotfix/,release/)
    required: false
    default: hotfix/,release/

runs:
  using: composite
  steps:
    - name: Validate source branch
      shell: bash
      run: |
        SOURCE_BRANCH="${{ github.head_ref || github.ref_name }}"
        echo "Source branch: ${SOURCE_BRANCH}"

        EXACT_RAW="${{ inputs.allowed_branches }}"
        PREFIX_RAW="${{ inputs.allowed_prefixes }}"
        # Remove spaces to avoid whitespace issues
        EXACT_RAW_NO_WS="$(echo "$EXACT_RAW" | tr -d ' ')"
        PREFIX_RAW_NO_WS="$(echo "$PREFIX_RAW" | tr -d ' ')"
        IFS=',' read -r -a EXACT <<< "$EXACT_RAW_NO_WS"
        IFS=',' read -r -a PREFIXES <<< "$PREFIX_RAW_NO_WS"

        ALLOWED=false

        # Check exact matches
        for b in "${EXACT[@]}"; do
          if [ -n "$b" ] && [ "$SOURCE_BRANCH" = "$b" ]; then
            ALLOWED=true
            break
          fi
        done

        # Check prefixes if not allowed yet
        if [ "$ALLOWED" = false ]; then
          for p in "${PREFIXES[@]}"; do
            if [ -n "$p" ] && [[ "$SOURCE_BRANCH" == "$p"* ]]; then
              ALLOWED=true
              break
            fi
          done
        fi

        if [ "$ALLOWED" = false ]; then
          echo "❌ Branch '${SOURCE_BRANCH}' is not allowed."
          echo "   Allowed exact branches: '${EXACT_RAW_NO_WS}'"
          echo "   Allowed prefixes: '${PREFIX_RAW_NO_WS}'"
          exit 1
        fi