name: dev_pr

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/workflows/dev_pr.yml@main
    secrets: inherit
