name: main_pr

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-source-branch:
    name: check-source-branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        uses: ./.github/actions/check-source-branch
        with:
          allowed_branches: dev
          allowed_prefixes: hotfix/,release/
  format:
    name: format
    needs: check-source-branch
    runs-on: ubuntu-latest
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: ./.github/actions/format
        with:
          pat_autofix: ${{ secrets.PAT_AUTOFIX }}
  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    needs: [format]
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run code quality action
        uses: ./.github/actions/code-quality

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - name: Run test action
        uses: ./.github/actions/test
