name: tag_on_merge

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/workflows/tag_on_merge.yml@main
    secrets: inherit
