name: publish_on_tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  get-workflow-type:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.get-workflow.outputs.workflow_type }}
    steps:
      - name: Get workflow type
        id: get-workflow
        uses: ./.github/actions/get-workflow-type

  call-reusable:
    needs: get-workflow-type
    uses: j-moralejo-pinas/ci-cd-python/.github/workflows/publish_on_tag.yml@main
    with:
      workflow_type: ${{ needs.get-workflow-type.outputs.workflow_type }}
    secrets: inherit
