name: release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python/.github/workflows/release.yml@main
    secrets: inherit
