name: release_on_merge

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/workflows/release_on_merge.yml@main
    secrets: inherit
