name: sync_main_to_dev

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/workflows/sync_main_to_dev.yml@main
    secrets: inherit
