name: Changelog slice between releases

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
      - 'major/**'

permissions:
  contents: write
  pull-requests: read

jobs:
  call-reusable:
    uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/workflows/update_changelog.yml@main
    secrets: inherit
